import type { Brand } from './types';

/**
 * Brands carried by the store.
 *
 * `logo` points at an official brand mark under /assets/brands. Those files are
 * generated by scripts/build-brand-logos.mjs (vendor glyph data from the
 * `simple-icons` package) and scripts/fetch-commons-logos.mjs (vendor SVG artwork
 * from Wikimedia Commons for the marks simple-icons does not redistribute).
 * None of them is redrawn, recoloured or substituted with a text label.
 */
export const brands: Brand[] = [
  {
    id: 'apple',
    name: 'Apple',
    logo: '/assets/brands/apple.svg',
    description: 'iPhone, Mac, iPad and Watch',
    website: 'https://www.apple.com',
    theme: 'light',
  },
  {
    id: 'samsung',
    name: 'Samsung',
    logo: '/assets/brands/samsung.svg',
    description: 'Galaxy phones, tablets and wearables',
    website: 'https://www.samsung.com',
    theme: 'light',
  },
  {
    id: 'sony',
    name: 'Sony',
    logo: '/assets/brands/sony.svg',
    description: 'PlayStation, Alpha cameras and audio',
    website: 'https://www.sony.com',
    theme: 'dark',
  },
  {
    id: 'google',
    name: 'Google',
    logo: '/assets/brands/google.svg',
    description: 'Pixel phones, buds and watches',
    website: 'https://store.google.com',
    theme: 'light',
  },
  {
    id: 'microsoft',
    name: 'Microsoft',
    logo: '/assets/brands/microsoft.svg',
    description: 'Surface and Xbox',
    website: 'https://www.microsoft.com',
    theme: 'light',
  },
  {
    id: 'asus',
    name: 'ASUS',
    logo: '/assets/brands/asus.svg',
    description: 'ROG gaming and Zenbook laptops',
    website: 'https://www.asus.com',
    theme: 'dark',
  },
  {
    id: 'lenovo',
    name: 'Lenovo',
    logo: '/assets/brands/lenovo.svg',
    description: 'ThinkPad, Yoga and Legion',
    website: 'https://www.lenovo.com',
    theme: 'light',
  },
  {
    id: 'dell',
    name: 'Dell',
    logo: '/assets/brands/dell.svg',
    description: 'XPS laptops and displays',
    website: 'https://www.dell.com',
    theme: 'light',
  },
  {
    id: 'hp',
    name: 'HP',
    logo: '/assets/brands/hp.svg',
    description: 'Spectre and Envy notebooks',
    website: 'https://www.hp.com',
    theme: 'light',
  },
  {
    id: 'logitech',
    name: 'Logitech',
    logo: '/assets/brands/logitech.svg',
    description: 'Mice, keyboards and webcams',
    website: 'https://www.logitech.com',
    theme: 'light',
  },
  {
    id: 'jbl',
    name: 'JBL',
    logo: '/assets/brands/jbl.svg',
    description: 'Portable and home speakers',
    website: 'https://www.jbl.com',
    theme: 'light',
  },
  {
    id: 'bose',
    name: 'Bose',
    logo: '/assets/brands/bose.svg',
    description: 'Noise cancelling headphones',
    website: 'https://www.bose.com',
    theme: 'light',
  },
  {
    id: 'canon',
    name: 'Canon',
    logo: '/assets/brands/canon.svg',
    description: 'EOS mirrorless cameras and lenses',
    website: 'https://www.canon.com',
    theme: 'light',
  },
  {
    id: 'nikon',
    name: 'Nikon',
    logo: '/assets/brands/nikon.svg',
    description: 'Z-series mirrorless systems',
    website: 'https://www.nikon.com',
    theme: 'light',
  },
  {
    id: 'nintendo',
    name: 'Nintendo',
    logo: '/assets/brands/nintendo.svg',
    description: 'Switch consoles and games',
    website: 'https://www.nintendo.com',
    theme: 'light',
  },
  {
    id: 'playstation',
    name: 'PlayStation',
    logo: '/assets/brands/playstation.svg',
    description: 'Consoles, controllers and accessories',
    website: 'https://www.playstation.com',
    theme: 'dark',
  },
  {
    id: 'xbox',
    name: 'Xbox',
    logo: '/assets/brands/xbox.svg',
    description: 'Series X|S consoles and controllers',
    website: 'https://www.xbox.com',
    theme: 'dark',
  },
];

const brandIndex = new Map(brands.map((b) => [b.id, b]));

export const getBrand = (id: string): Brand | undefined => brandIndex.get(id);

/** Brand name for display, falling back to the raw id so UI never renders blank. */
export const brandName = (id: string): string => brandIndex.get(id)?.name ?? id;
